Repository alexmkio/rancid-tomatillos, pull requests merged in 2021-07, with the labels that each got.

#21 Create initial file structure
  src/App.js
  src/components/app/App.css
  src/components/app/App.js
  src/components/app/App.test.js
  src/components/movie_details/MovieDetails.css
  src/components/movie_details/MovieDetails.js
  src/components/poster/Poster.css
  src/components/poster/Poster.js
  src/components/posters/Posters.css
  src/components/posters/Posters.js
  src/index.js
  src/movieData.js
Labels: it1

#24 Fetch data from API, error handling, and add placeholders while waiting for fetch to complete
  src/apiCalls.js
  src/components/app/App.js
  src/components/error_code/ErrorCode.css
  src/components/error_code/ErrorCode.js
  src/components/poster/Poster.css
  src/components/poster/Poster.js
  src/components/posters/Posters.js
  src/httpResponses.js
  src/movieData.js
Labels: API

#26 Refactor/api movie details
  src/components/movie_details/MovieDetails.css
  src/components/movie_details/MovieDetails.js
  src/components/poster/Poster.css
Labels: API, FIRST WEEKEND DELIVERABLES, it3

#27 Add PropTypes
  package-lock.json
  package.json
  src/components/error_code/ErrorCode.js
  src/components/movie_details/MovieDetails.js
  src/components/poster/Poster.js
  src/components/posters/Posters.js
Labels: Testing

#29 Remove isRequired for two propType checks
  src/components/error_code/ErrorCode.js
Labels: Refactor

#31 Add Router
  package-lock.json
  package.json
  src/components/app/App.js
  src/components/error_code/ErrorCode.js
  src/components/movie_details/MovieDetails.js
  src/components/poster/Poster.js
  src/components/posters/Posters.js
  src/index.js
Labels: Router

#32 When a user visits "/*" should see an error page if * isn't a movie.id
  src/components/app/App.js
Labels: Router

#33 Testing/dashboard
  cypress.json
  cypress/integration/dashboard_spec.js
  package-lock.json
  package.json
Labels: Testing

#34 Testing/movie details
  cypress/integration/movie_details_spec.js
Labels: Testing

#35 Refactor fetch calls for user story starting at url/movieID
  src/components/app/App.js
  src/components/movie_details/MovieDetails.js
Labels: API, Refactor, Router

#37 Replace toFixed with Math.round
  src/components/movie_details/MovieDetails.js
Labels: Refactor

#38 Add commas to large numbers
  src/components/movie_details/MovieDetails.js
Labels: Refactor

#39 Refactor propTypes for MovieDetails component
  src/components/app/App.js
  src/components/movie_details/MovieDetails.js
Labels: Testing

#41 Update 404 page tests
  cypress/integration/movie_details_spec.js
Labels: Refactor, Testing

#43 Testing/loading screens
  cypress/integration/dashboard_spec.js
  cypress/integration/movie_details_spec.js
Labels: Testing, it5

#44 Clean fetched data (reformat certain values and remove unused data before setting to state)
  src/components/app/App.js
  src/components/movie_details/MovieDetails.js
  src/utilities.js
Labels: API

#45 Feature/responsive design
  public/favicon.ico
  public/index.html
  src/components/app/App.css
  src/components/movie_details/MovieDetails.css
  src/components/poster/Poster.css
  src/components/posters/Posters.css
Labels: enhancement

#51 Conditionally render more movie detail data
  src/apiCalls.js
  src/components/app/App.js
  src/components/movie_details/MovieDetails.js
  src/utilities.js
Labels: Refactor

#49 Add mobile media query and styling for error page
  src/components/error_code/ErrorCode.css
Labels: Refactor

#53 Refactor/fetch fn
  src/components/app/App.js
  src/components/movie_details/MovieDetails.js
  src/components/poster/Poster.js
  src/utilities.js
Labels: Refactor

#54 Refactor componentDidMount and render into arrow functions
  src/components/app/App.js
  src/components/error_code/ErrorCode.js
  src/components/movie_details/MovieDetails.js
  src/components/poster/Poster.js
  src/components/posters/Posters.js
Labels: Refactor

#55 Refactor/initial state values
  src/components/app/App.js
  src/components/movie_details/MovieDetails.js
  src/components/poster/Poster.js
Labels: Refactor
